/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dtos.DetalleVentaDTO;
import dtos.VentaDTO;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marki
 */
public class PantallaReporteVentas extends javax.swing.JFrame {
    private JTextField txtFechaInicio;
    private JTextField txtFechaFin;
    private JButton btnGenerar;

    private JLabel lblTotalIngresos;
    private JLabel lblKilosVendidos;

    private JTable tablaVentas;
    private DefaultTableModel modelo;
    /**
     * Creates new form PantallaReporteVentas
     */
    public PantallaReporteVentas() {

        setTitle("Reporte de Ventas");
        setSize(900, 600);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());

        //Filtros
        JPanel panelFiltros = new JPanel();
        panelFiltros.add(new JLabel("Inicio:"));
        txtFechaInicio = new JTextField(10);
        panelFiltros.add(txtFechaInicio);

        panelFiltros.add(new JLabel("Fin:"));
        txtFechaFin = new JTextField(10);
        panelFiltros.add(txtFechaFin);

        btnGenerar = new JButton("Generar");
        panelFiltros.add(btnGenerar);

        add(panelFiltros, BorderLayout.NORTH);

        // Centro
        JPanel panelCentro = new JPanel(new BorderLayout());

        JPanel panelResumen = new JPanel(new GridLayout(1, 2));
        lblTotalIngresos = new JLabel("Total: $0");
        lblKilosVendidos = new JLabel("Kilos: 0");

        panelResumen.add(lblTotalIngresos);
        panelResumen.add(lblKilosVendidos);

        panelCentro.add(panelResumen, BorderLayout.NORTH);

        // Tabla 
        modelo = new DefaultTableModel(
                new Object[]{"Fecha", "Cantidad", "Total"}, 0
        );

        tablaVentas = new JTable(modelo);
        panelCentro.add(new JScrollPane(tablaVentas), BorderLayout.CENTER);

        add(panelCentro, BorderLayout.CENTER);
    }
    
    public void setGenerarListener(ActionListener listener) {
        btnGenerar.addActionListener(listener);
    }
    public void mostrarDatos(List<VentaDTO> ventas) {
        modelo.setRowCount(0);

        double total = 0;
        double kilosTotales = 0;

        for (VentaDTO v : ventas) {
            double kilosDeEstaVenta = 0.0;
            if (v.getProductos() != null) {
                for (DetalleVentaDTO producto : v.getProductos()) {
                    kilosDeEstaVenta += producto.getCantidadKilos();
                }
            }

            modelo.addRow(new Object[]{
                    v.getFechaHora(),      
                    kilosDeEstaVenta,       
                    v.getMontoTotal()
            });

            total += v.getMontoTotal();
            kilosTotales += kilosDeEstaVenta;
        }

        lblTotalIngresos.setText("Total: $" + total);
        lblKilosVendidos.setText("Kilos: " + kilosTotales);
    }
    
    public LocalDate getFechaInicio() { 
        try{
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        return LocalDate.parse(txtFechaInicio.getText().trim(),formatter);
        }catch(Exception e){
            throw new RuntimeException("Fecha de inicio inválida: " +txtFechaInicio.getText());
        }
    }
    
    public LocalDate getFechaFin() { 
        try{
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        return LocalDate.parse(txtFechaFin.getText().trim(),formatter);
        }catch(Exception e){
            throw new RuntimeException("Fecha de fin inválida: " +txtFechaFin.getText());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
